### ISSUE TITLE
Backend tests are failing on develop branch

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-ml#30]
Something's wrong with the Travis tests on the develop branch. They keep failing due to classification taking longer than expected (I think):

https://travis-ci.org/oppia/oppia-ml/jobs/462211596

We could increase the timeout but I suspect this shadows a bigger problem, since the only recent change was the README. It might be worth investigating why the latency has increased.

**Comment by shaz13** [comment]
I checked with the code. The code seems to be using CountVectorizer on text also an SVM Classifier. When huge dataset and vocabulary is passed then vectorization especially count can be heavy, both while transforming vectors and classification. 

I suspect this might be causing the longer train/prediction. 

One of the way to avoid this is setting max_df to `.80`. Ref [max_df](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).

**Comment by prasanna08** [comment]
Hi @shaz13, sure, I will assign this to you.

Regarding the issue: I agree that CV can take time, however, since this is the same dataset on which test suite created, I don't think that is the issue here. I looked at the logs and execution time is `2.294534921646118` whereas the expected time is 2 seconds. TBH, this is just a few milliseconds here and there. I suspect this is internal to Travis VM (processor clocks/speed changes). I suspect if Travis changed the configuration of their VMs they provide to open source projects. 

One thing you can try is to determine the average running time on your local system and see  how is it different from Travis. If it fails on local system as well then there is something deeper than I think. Otherwise, this could be caused due to Travis's changes in their VM configurations.

Thanks.

**Comment by prasanna08** [comment]
I re-ran the tests and it ran fine. These are just glitches that should be expected in a real world system. I don't think there is anything else to do here.

**Comment by prasanna08** [comment]
Closing this, since tests are running fine on `develop`.
