### ISSUE TITLE
Implement main worker process.

### ISSUE THREAD

**Issue by prasanna08** [oppia/oppia-ml#7]
* Implement main worker process which will poll <--> train <--> save job requests. The main worker process is same as [polling](https://docs.google.com/document/d/1kACmivEvZVlTYBdqxy-mmdTi3sg_NbkZdS10T-ya-pg/edit#heading=h.p3ovq6xw17r5) (as described in doc) process of VM.
* Implement `algorithm_registry` for algorithm_id <--> classifier mapping.
* Incorporate logging module to display log.

**Comment by anmolshkl** [comment]
@prasanna08 before starting with this issue it might be a better idea to define what a classifier is going to be like (since your algorithm_registry will return a classifier). What exactly are we supposed to return to the user, an instance of the classifier or the class? I think the issue needs more detailing.

**Comment by prasanna08** [comment]
Classifier -- classifier is a class developed by user which takes in raw training data obtained from job request and returns trained model in dict format. It uses other 3rd party libraries for implementing required model. Does that clarify what I mean by classifier?

algorithm_registry -- returns an instance of classifier. So it returns instance of a classifier which is implemented as a class by developer. Does that clear your doubt?

**Comment by anmolshkl** [comment]
@prasanna08 thanks, that does help. I think it would be better if there existed a classifier before you made an algorithm_registry (since there would be something to return and test with). 

Also, [earlier](https://github.com/oppia/oppia/pull/3306/files#diff-a054b676c6dbe19eabed38275a980fb0R114) we had concluded that returning a class of the the algorithm is better than returning an instance. I don't think the same use case applies here but it might be worth checking out.

**Comment by prasanna08** [comment]
@anmolshkl I don't see what difference it makes whether we return a class or instance of class. Perhaps you can tell me why you decided to return a class earlier?

algorithm_registry: yes it would have been better if we had some existing classifier to test it with but we can do that later too, once we do have some classifier to test the registry.

**Comment by seanlip** [comment]
Technically, instance or class doesn't really matter here. But I think a class might make more sense conceptually since presumably the point is that there's just one object here? If for some reason you need to parameterize it then instances would make sense.
